In [81]:
import pandas as pd
import numpy  as np
from   scipy  import stats

from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import StandardScaler
from sklearn.decomposition   import PCA
from sklearn.metrics         import accuracy_score
from sklearn.neighbors       import KNeighborsClassifier
from sklearn.svm             import SVC 
from sklearn.ensemble        import RandomForestClassifier 
from sklearn.naive_bayes     import GaussianNB

pd.options.mode.chained_assignment = None

LUMINAL_A = "Luminal A    "
LUMINAL_B = "Luminal B    "

### Dataset exploration

In [88]:
luminal_A_B_df = pd.read_csv("dataset_LUMINAL_A_B.csv").rename(columns={'l': 'Label'})

genes = list(luminal_A_B_df.columns)
genes.remove("Label")

luminal_A_B_df.head()

,Label,ENSG00000242268.2,ENSG00000270112.3,ENSG00000167578.15,ENSG00000273842.1,ENSG00000078237.5,ENSG00000146083.10,ENSG00000225275.4,ENSG00000158486.12,ENSG00000198242.12,...,ENSG00000088356.5,ENSG00000176752.6,ENSG00000223082.1,ENSG00000237714.1,ENSG00000200959.1,ENSG00000270971.2,ENSG00000267313.5,ENSG00000151632.15,ENSG00000269107.1,ENSG00000268889.1
0,Luminal A,2356.253792,26808.891103,57790.161586,0.0,71389.111749,381288.489078,0.0,1677.413295,1.969141e+06,...,113036.499486,0.0,20911.752405,13957.784680,1.047700e+06,0.0,1937.768563,10731.974977,0.0,0.0
1,Luminal A,0.000000,231.960840,115769.964478,0.0,77938.573803,238017.846096,0.0,0.000000,4.865670e+06,...,850405.301444,0.0,0.000000,2122.068451,0.000000e+00,0.0,5499.352680,2479.070667,0.0,0.0
2,Luminal A,0.000000,315.873536,44954.933833,0.0,58546.997851,249302.406604,0.0,270.107768,2.519212e+06,...,301948.579552,0.0,0.000000,481.622432,0.000000e+00,0.0,312.031830,4822.690978,0.0,0.0
3,Luminal A,1074.333108,0.000000,86991.783442,0.0,36082.381881,176274.146728,0.0,101.975469,2.855010e+06,...,293581.147891,0.0,0.000000,0.000000,0.000000e+00,0.0,0.000000,12631.387770,0.0,0.0
4,Luminal A,1395.887715,0.000000,65199.337535,0.0,91469.201926,263704.398926,0.0,66.248682,4.235429e+06,...,350449.557585,0.0,0.000000,1181.263740,0.000000e+00,0.0,0.000000,1626.418477,0.0,0.0

In [22]:
luminal_A_df = luminal_A_B_df[luminal_A_B_df.Label == LUMINAL_A].drop("Label", axis=1)
luminal_A_df.head()

,ENSG00000242268.2,ENSG00000270112.3,ENSG00000167578.15,ENSG00000273842.1,ENSG00000078237.5,ENSG00000146083.10,ENSG00000225275.4,ENSG00000158486.12,ENSG00000198242.12,ENSG00000259883.1,...,ENSG00000088356.5,ENSG00000176752.6,ENSG00000223082.1,ENSG00000237714.1,ENSG00000200959.1,ENSG00000270971.2,ENSG00000267313.5,ENSG00000151632.15,ENSG00000269107.1,ENSG00000268889.1
0,2356.253792,26808.891103,57790.161586,0.0,71389.111749,381288.489078,0.0,1677.413295,1.969141e+06,86793.265493,...,113036.499486,0.0,20911.752405,13957.784680,1.047700e+06,0.0,1937.768563,10731.974977,0.0,0.0
1,0.000000,231.960840,115769.964478,0.0,77938.573803,238017.846096,0.0,0.000000,4.865670e+06,769.742944,...,850405.301444,0.0,0.000000,2122.068451,0.000000e+00,0.0,5499.352680,2479.070667,0.0,0.0
2,0.000000,315.873536,44954.933833,0.0,58546.997851,249302.406604,0.0,270.107768,2.519212e+06,2620.500780,...,301948.579552,0.0,0.000000,481.622432,0.000000e+00,0.0,312.031830,4822.690978,0.0,0.0
3,1074.333108,0.000000,86991.783442,0.0,36082.381881,176274.146728,0.0,101.975469,2.855010e+06,9893.339903,...,293581.147891,0.0,0.000000,0.000000,0.000000e+00,0.0,0.000000,12631.387770,0.0,0.0
4,1395.887715,0.000000,65199.337535,0.0,91469.201926,263704.398926,0.0,66.248682,4.235429e+06,2570.895661,...,350449.557585,0.0,0.000000,1181.263740,0.000000e+00,0.0,0.000000,1626.418477,0.0,0.0

In [23]:
luminal_B_df = luminal_A_B_df[luminal_A_B_df.Label == LUMINAL_B].drop("Label", axis=1)
luminal_B_df.head()

,ENSG00000242268.2,ENSG00000270112.3,ENSG00000167578.15,ENSG00000273842.1,ENSG00000078237.5,ENSG00000146083.10,ENSG00000225275.4,ENSG00000158486.12,ENSG00000198242.12,ENSG00000259883.1,...,ENSG00000088356.5,ENSG00000176752.6,ENSG00000223082.1,ENSG00000237714.1,ENSG00000200959.1,ENSG00000270971.2,ENSG00000267313.5,ENSG00000151632.15,ENSG00000269107.1,ENSG00000268889.1
50,472.317473,0.000000,43185.197034,0.0,71328.844164,197593.096861,0.0,381.074325,2.544896e+06,3914.537811,...,168679.746145,0.0,0.000000,1598.786202,1693.663665,0.0,0.000000,26915.683769,0.0,0.000000
51,0.000000,0.000000,115939.159122,0.0,97148.626331,197179.900505,0.0,177.495804,6.747133e+06,1722.008578,...,359360.954156,0.0,3319.171535,0.000000,0.000000,0.0,102.522673,396.141612,0.0,1425.046813
52,0.000000,61.848883,45418.241007,0.0,36746.522566,219188.070354,0.0,359.637198,9.354113e+06,1231.442546,...,119115.871944,0.0,0.000000,1131.635522,0.000000,0.0,0.000000,472.147895,0.0,566.155160
53,0.000000,0.000000,89420.856204,0.0,80340.679862,241397.554846,0.0,59.576577,2.894877e+06,4045.952776,...,288613.033711,0.0,0.000000,1062.295110,9002.682799,0.0,0.000000,2393.373228,0.0,0.000000
54,0.000000,0.000000,218106.422474,0.0,86026.755295,228346.920871,0.0,4887.091780,2.897671e+06,3818.499101,...,455313.016648,0.0,12266.928361,0.000000,2478.167346,0.0,0.000000,3879.738643,0.0,0.000000

### Assignment 1: T-test to perform differential gene expression analysis

Perform a differential gene expression analysis on dataset_LUMINAL_A_B.csv in order to find which genes are able to distinguish between breast cancer Luminal A subtype and breast cancer Luminal B subtype.<br>
* Calculate t-value and p-value for each gene and select only genes for which p-value < adjusted Bonferroni p-value. <br>
* Finally, convert differentially expressed genes from ENSEMBL notation to the common name (e.g. ENSG00000268889 is AC008750). <br>
* Which genes are differentially expressed between the two populations? <br>
* Create now a reduced dataset (from now on referred to as reduced_dataset.csv) made up of all samples with only differentially expressed genes (use common name notation).

In [24]:
ALPHA              = 0.05
BONFERRONI_P_VALUE = ALPHA / len(genes)

differentially_expressed_genes = perform_ttest(luminal_A_df, luminal_B_df, genes)

list(differentially_expressed_genes.keys())

['ENSG00000174013',
 'ENSG00000109805',
 'ENSG00000127329',
 'ENSG00000269113',
 'ENSG00000049239',
 'ENSG00000267206',
 'ENSG00000175643',
 'ENSG00000085999',
 'ENSG00000167178']

In [25]:
GTF_FILE = "Homo_sapiens.GRCh38.95.gtf"

file   = parse_gtf(GTF_FILE, prune = True)
gtf_df = pd.DataFrame(file, columns={"GeneId", "GeneName"})

gtf_df

                GeneId     GeneName
0      ENSG00000223972      DDX11L1
1      ENSG00000227232       WASH7P
2      ENSG00000278267    MIR6859-1
3      ENSG00000243485  MIR1302-2HG
4      ENSG00000284332    MIR1302-2
...                ...          ...
58730  ENSG00000271254   AC240274.1
58731  ENSG00000275405      RF00003
58732  ENSG00000275987      RF00003
58733  ENSG00000277475   AC213203.2
58734  ENSG00000268674   AC213203.1

[58735 rows x 2 columns]

In [26]:
differentially_expressed_genes_common_name = convert_ENSEMBL_to_common_name(gtf_df, differentially_expressed_genes)
differentially_expressed_genes_common_name

                GeneId GeneName          FullGeneId
313    ENSG00000049239     H6PD  ENSG00000049239.11
1480   ENSG00000085999   RAD54L  ENSG00000085999.10
1528   ENSG00000269113  TRABD2B   ENSG00000269113.3
12320  ENSG00000174013   FBXO45   ENSG00000174013.7
12744  ENSG00000109805    NCAPG   ENSG00000109805.8
30524  ENSG00000267206     LCN6   ENSG00000267206.4
37901  ENSG00000127329    PTPRB  ENSG00000127329.13
44125  ENSG00000167178    ISLR2  ENSG00000167178.14
45354  ENSG00000175643     RMI2   ENSG00000175643.8

In [27]:
reduced_df = get_reduced_dataframe(luminal_A_df, luminal_B_df, differentially_expressed_genes_common_name, differentially_expressed_genes)
reduced_df

,FBXO45,NCAPG,PTPRB,TRABD2B,H6PD,LCN6,RMI2,RAD54L,ISLR2,Label
0,70825.613901,45214.599794,89617.687379,14032.338833,232427.588150,1990.410699,56982.783302,43229.774585,1919.452769,Luminal A
1,84313.515188,33888.554894,35178.978153,13246.385298,152172.258997,1412.187531,54930.748805,21248.212379,2237.313823,Luminal A
2,98586.080863,27754.410175,41236.180097,21312.785434,310354.839213,0.000000,99935.673890,19625.364375,8941.315316,Luminal A
3,97516.942931,45261.276142,39602.273580,9976.604862,181590.072727,9075.270749,253317.484752,46308.038220,9001.787980,Luminal A
4,162775.316661,83278.133458,8825.807725,3663.361845,275495.011159,0.000000,431694.167524,67265.099781,1705.678235,Luminal A
...,...,...,...,...,...,...,...,...,...,...
95,114970.162862,82283.925849,14565.406636,6473.284423,255328.468855,0.000000,160149.679744,64677.674191,5597.412223,Luminal B
96,151514.339106,182911.854614,27209.399482,9593.960471,309027.642543,577.627380,135349.258381,64239.016300,4058.398040,Luminal B
97,195692.063713,152029.402486,21932.504709,5038.108291,101626.950007,669.254954,320303.042499,125916.506673,7283.755835,Luminal B
98,182627.081916,153069.027034,40141.162530,5321.918640,284361.807447,181.049684,139383.253891,85277.106536,1197.224788,Luminal B
99,250981.116327,67854.326254,62938.038743,14837.935631,242033.959906,868.364562,89037.025723,25222.448934,10048.889492,Luminal B

#### Code

In [28]:
def parse_gtf(filename, prune = True):
    
    file = list()
    
    with open(filename, "r") as f:
        for line in f: 
            if line.startswith("#") == False:
                row = [x.replace('\n', '') for x in line.split('\t')]
                
                if row[2] == "gene":
                    row = row[8].split(";")
                    row = [r for r in row if len(r) > 0]
                    
                    gene_id   = str(list(filter(lambda x: x != "", row[0].split("\"")))[1])
                    gene_name = str(list(filter(lambda x: x != "", row[2].split("\"")))[1])
                    
                    file.append([gene_id, gene_name])
        
    return file

def perform_ttest(luminal_A_df, luminal_B_df, genes):
    global BONFERRONI_P_VALUE
    
    differentially_expressed_genes = list()
    
    for gene in genes:
        t, p = stats.ttest_ind(np.array(luminal_A_df[gene]), np.array(luminal_B_df[gene]), equal_var = False)
        
        if p < BONFERRONI_P_VALUE:
            differentially_expressed_genes.append(gene)
            
    return {gene.split(".")[0]:gene for gene in differentially_expressed_genes}

def convert_ENSEMBL_to_common_name(gtf_df, differentially_expressed_genes):
   
    differentially_expressed_genes_common_name               = gtf_df[gtf_df.GeneId.isin(differentially_expressed_genes.keys())]
    differentially_expressed_genes_common_name["FullGeneId"] = differentially_expressed_genes_common_name.GeneId.map(differentially_expressed_genes)
    
    return differentially_expressed_genes_common_name

def get_reduced_dataframe(reduced_luminal_A_df, reduced_luminal_B_df, differentially_expressed_genes_common_name, differentially_expressed_genes):

    columns_map = dict(zip(differentially_expressed_genes_common_name.FullGeneId, differentially_expressed_genes_common_name.GeneName)) 

    reduced_luminal_A_df = luminal_A_df[differentially_expressed_genes.values()].rename(columns = columns_map)
    reduced_luminal_B_df = luminal_B_df[differentially_expressed_genes.values()].rename(columns = columns_map)

    reduced_luminal_A_df["Label"] = "Luminal A"
    reduced_luminal_B_df["Label"] = "Luminal B"

    return pd.concat([reduced_luminal_A_df, reduced_luminal_B_df])

### Assignment 2: Use gene expression data to create a classifier for Luminal A / Luminal B breast cancer subtypes

In order to create a Luminal A / Luminal B breast cancer classifier, consider two dataset: dataset_LUMINAL_A_B.csv and reduced_dataset.csv.
1. Divide both dataset_LUMINAL_A_B.csv and reduced_dateset.csv into train set and test set
2. Standardize features of both datasets by removing the mean and scaling to unit variance
3. Perform the dimensionality reduction onto dataset.csv with PCA (principal component Analysis) using
80 features.
4. Train a KNN classifier onto the train set of dataset_LUMINAL_A_B.csv with PCA
5. Test the classifier obtained at the previous step onto the test set of dataset_LUMINAL_A_B.csv
(remember to apply PCA transformation onto test set)
6. Train and test a KNN classifier onto reduced_dataset.csv
7. Which are the differences between the performances obtained onto
dataset_LUMINAL_A_B.csv with PCA and these obtained onto reduced_dataset.csv?
8. Use reduced_dataset.csv to train and test (with default parameters) SVM, Random Forest and
NaÃ¯ve Bayes classifiers
9. Which classifier provides you the best result on reduced_dataset.csv?

In [44]:
# 1.
luminal_A_B_X_train, luminal_A_B_X_test, luminal_A_B_y_train, luminal_A_B_y_test = split_dataset(luminal_A_B_df)
reduced_X_train, reduced_X_test, reduced_y_train, reduced_y_test                 = split_dataset(reduced_df)

In [45]:
# 2.
scaler = StandardScaler()

scaled_luminal_A_B_X_train, scaled_luminal_A_B_X_test = apply_scaler(scaler, luminal_A_B_X_train, luminal_A_B_X_test)
scaled_reduced_X_train, scaled_reduced_X_test         = apply_scaler(scaler, reduced_X_train, reduced_X_test)

In [46]:
# 3.
pca = PCA(n_components=80)

dr_luminal_A_B_X_train = pca.fit_transform(luminal_A_B_X_train)
dr_luminal_A_B_X_test  = pca.transform    (luminal_A_B_X_test)

In [87]:
# 4, 5.
train_classifier(
    clf     = KNeighborsClassifier(),
    X_train = dr_luminal_A_B_X_train,
    y_train = luminal_A_B_y_train,
    X_test  = dr_luminal_A_B_X_test,
    y_test  = luminal_A_B_y_test
)

'Accuracy: 0.6'

In [86]:
# 6.
train_classifier(
    clf     = KNeighborsClassifier(),
    X_train = scaled_reduced_X_train,
    y_train = reduced_y_train,
    X_test  = scaled_reduced_X_test,
    y_test  = reduced_y_test
)

'Accuracy: 0.75'

In [83]:
# 8. - Best classifier
train_classifier(
    clf     = SVC(),
    X_train = scaled_reduced_X_train,
    y_train = reduced_y_train,
    X_test  = scaled_reduced_X_test,
    y_test  = reduced_y_test
)

'Accuracy: 0.9'

In [84]:
# 8.
train_classifier(
    clf     = RandomForestClassifier(),
    X_train = scaled_reduced_X_train,
    y_train = reduced_y_train,
    X_test  = scaled_reduced_X_test,
    y_test  = reduced_y_test
)

'Accuracy: 0.75'

In [89]:
# 8. - Best classifier
train_classifier(
    clf     = GaussianNB(),
    X_train = scaled_reduced_X_train,
    y_train = reduced_y_train,
    X_test  = scaled_reduced_X_test,
    y_test  = reduced_y_test
)

'Accuracy: 0.9'

#### Code

In [90]:
def split_dataset(df):
    X = df.drop("Label", axis=1)
    y = df["Label"]
    return train_test_split(X, y, test_size=0.2)

def apply_scaler(scaler, X_train, X_test):
    scaled_X_train = scaler.fit_transform(X_train)
    scaled_X_test  = scaler.transform    (X_test)
    
    return scaled_X_train, scaled_X_test

def train_classifier(clf, X_train, y_train, X_test, y_test):
    
    clf.fit(X_train, y_train) 
    predictions = clf.predict(X_test)

    return "Accuracy: " + str(accuracy_score(y_test, predictions))